// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: beeremote.proto

package beeremote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BeeRemote_SubmitJob_FullMethodName      = "/beeremote.BeeRemote/SubmitJob"
	BeeRemote_UpdatePaths_FullMethodName    = "/beeremote.BeeRemote/UpdatePaths"
	BeeRemote_UpdateJobs_FullMethodName     = "/beeremote.BeeRemote/UpdateJobs"
	BeeRemote_GetJobs_FullMethodName        = "/beeremote.BeeRemote/GetJobs"
	BeeRemote_UpdateWork_FullMethodName     = "/beeremote.BeeRemote/UpdateWork"
	BeeRemote_GetRSTConfig_FullMethodName   = "/beeremote.BeeRemote/GetRSTConfig"
	BeeRemote_GetGlobalFlags_FullMethodName = "/beeremote.BeeRemote/GetGlobalFlags"
)

// BeeRemoteClient is the client API for BeeRemote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Externally facing RPCs and messages clients and worker nodes use to interact
// with BeeRemote.
type BeeRemoteClient interface {
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	UpdatePaths(ctx context.Context, in *UpdatePathsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdatePathsResponse], error)
	UpdateJobs(ctx context.Context, in *UpdateJobsRequest, opts ...grpc.CallOption) (*UpdateJobsResponse, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetJobsResponse], error)
	// Rather then BeeRemote connecting to a worker node and using a streaming RPC to return work
	// results, we have BeeRemote expose a unary RPC that is used to send results back as they are
	// available. This allows us to avoid complex error handling needed to reliably use streams, and
	// more easily adhere to our requirement that work requests are always owned by BeeRemote or its
	// worker nodes and no polling is needed to check on the state of the requests. With this
	// approach either side can make an unary request for a particular work request, and look at the
	// response to verify ownership has successfully move to the other node (i.e., the node has
	// committed the request to its on-disk database). IMPORTANT: This is only intended to be called
	// by worker nodes.
	UpdateWork(ctx context.Context, in *UpdateWorkRequest, opts ...grpc.CallOption) (*UpdateWorkResponse, error)
	GetRSTConfig(ctx context.Context, in *GetRSTConfigRequest, opts ...grpc.CallOption) (*GetRSTConfigResponse, error)
	GetGlobalFlags(ctx context.Context, in *GetGlobalFlagsRequest, opts ...grpc.CallOption) (*GetGlobalFlagsResponse, error)
}

type beeRemoteClient struct {
	cc grpc.ClientConnInterface
}

func NewBeeRemoteClient(cc grpc.ClientConnInterface) BeeRemoteClient {
	return &beeRemoteClient{cc}
}

func (c *beeRemoteClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, BeeRemote_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beeRemoteClient) UpdatePaths(ctx context.Context, in *UpdatePathsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdatePathsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BeeRemote_ServiceDesc.Streams[0], BeeRemote_UpdatePaths_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdatePathsRequest, UpdatePathsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeeRemote_UpdatePathsClient = grpc.ServerStreamingClient[UpdatePathsResponse]

func (c *beeRemoteClient) UpdateJobs(ctx context.Context, in *UpdateJobsRequest, opts ...grpc.CallOption) (*UpdateJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobsResponse)
	err := c.cc.Invoke(ctx, BeeRemote_UpdateJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beeRemoteClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetJobsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BeeRemote_ServiceDesc.Streams[1], BeeRemote_GetJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetJobsRequest, GetJobsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeeRemote_GetJobsClient = grpc.ServerStreamingClient[GetJobsResponse]

func (c *beeRemoteClient) UpdateWork(ctx context.Context, in *UpdateWorkRequest, opts ...grpc.CallOption) (*UpdateWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkResponse)
	err := c.cc.Invoke(ctx, BeeRemote_UpdateWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beeRemoteClient) GetRSTConfig(ctx context.Context, in *GetRSTConfigRequest, opts ...grpc.CallOption) (*GetRSTConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRSTConfigResponse)
	err := c.cc.Invoke(ctx, BeeRemote_GetRSTConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beeRemoteClient) GetGlobalFlags(ctx context.Context, in *GetGlobalFlagsRequest, opts ...grpc.CallOption) (*GetGlobalFlagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalFlagsResponse)
	err := c.cc.Invoke(ctx, BeeRemote_GetGlobalFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeeRemoteServer is the server API for BeeRemote service.
// All implementations must embed UnimplementedBeeRemoteServer
// for forward compatibility.
//
// Externally facing RPCs and messages clients and worker nodes use to interact
// with BeeRemote.
type BeeRemoteServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	UpdatePaths(*UpdatePathsRequest, grpc.ServerStreamingServer[UpdatePathsResponse]) error
	UpdateJobs(context.Context, *UpdateJobsRequest) (*UpdateJobsResponse, error)
	GetJobs(*GetJobsRequest, grpc.ServerStreamingServer[GetJobsResponse]) error
	// Rather then BeeRemote connecting to a worker node and using a streaming RPC to return work
	// results, we have BeeRemote expose a unary RPC that is used to send results back as they are
	// available. This allows us to avoid complex error handling needed to reliably use streams, and
	// more easily adhere to our requirement that work requests are always owned by BeeRemote or its
	// worker nodes and no polling is needed to check on the state of the requests. With this
	// approach either side can make an unary request for a particular work request, and look at the
	// response to verify ownership has successfully move to the other node (i.e., the node has
	// committed the request to its on-disk database). IMPORTANT: This is only intended to be called
	// by worker nodes.
	UpdateWork(context.Context, *UpdateWorkRequest) (*UpdateWorkResponse, error)
	GetRSTConfig(context.Context, *GetRSTConfigRequest) (*GetRSTConfigResponse, error)
	GetGlobalFlags(context.Context, *GetGlobalFlagsRequest) (*GetGlobalFlagsResponse, error)
	mustEmbedUnimplementedBeeRemoteServer()
}

// UnimplementedBeeRemoteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBeeRemoteServer struct{}

func (UnimplementedBeeRemoteServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedBeeRemoteServer) UpdatePaths(*UpdatePathsRequest, grpc.ServerStreamingServer[UpdatePathsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UpdatePaths not implemented")
}
func (UnimplementedBeeRemoteServer) UpdateJobs(context.Context, *UpdateJobsRequest) (*UpdateJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobs not implemented")
}
func (UnimplementedBeeRemoteServer) GetJobs(*GetJobsRequest, grpc.ServerStreamingServer[GetJobsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedBeeRemoteServer) UpdateWork(context.Context, *UpdateWorkRequest) (*UpdateWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWork not implemented")
}
func (UnimplementedBeeRemoteServer) GetRSTConfig(context.Context, *GetRSTConfigRequest) (*GetRSTConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRSTConfig not implemented")
}
func (UnimplementedBeeRemoteServer) GetGlobalFlags(context.Context, *GetGlobalFlagsRequest) (*GetGlobalFlagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalFlags not implemented")
}
func (UnimplementedBeeRemoteServer) mustEmbedUnimplementedBeeRemoteServer() {}
func (UnimplementedBeeRemoteServer) testEmbeddedByValue()                   {}

// UnsafeBeeRemoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeeRemoteServer will
// result in compilation errors.
type UnsafeBeeRemoteServer interface {
	mustEmbedUnimplementedBeeRemoteServer()
}

func RegisterBeeRemoteServer(s grpc.ServiceRegistrar, srv BeeRemoteServer) {
	// If the following call pancis, it indicates UnimplementedBeeRemoteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BeeRemote_ServiceDesc, srv)
}

func _BeeRemote_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeeRemoteServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeeRemote_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeeRemoteServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeeRemote_UpdatePaths_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdatePathsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeeRemoteServer).UpdatePaths(m, &grpc.GenericServerStream[UpdatePathsRequest, UpdatePathsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeeRemote_UpdatePathsServer = grpc.ServerStreamingServer[UpdatePathsResponse]

func _BeeRemote_UpdateJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeeRemoteServer).UpdateJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeeRemote_UpdateJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeeRemoteServer).UpdateJobs(ctx, req.(*UpdateJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeeRemote_GetJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeeRemoteServer).GetJobs(m, &grpc.GenericServerStream[GetJobsRequest, GetJobsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BeeRemote_GetJobsServer = grpc.ServerStreamingServer[GetJobsResponse]

func _BeeRemote_UpdateWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeeRemoteServer).UpdateWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeeRemote_UpdateWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeeRemoteServer).UpdateWork(ctx, req.(*UpdateWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeeRemote_GetRSTConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRSTConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeeRemoteServer).GetRSTConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeeRemote_GetRSTConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeeRemoteServer).GetRSTConfig(ctx, req.(*GetRSTConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeeRemote_GetGlobalFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeeRemoteServer).GetGlobalFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeeRemote_GetGlobalFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeeRemoteServer).GetGlobalFlags(ctx, req.(*GetGlobalFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeeRemote_ServiceDesc is the grpc.ServiceDesc for BeeRemote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeeRemote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beeremote.BeeRemote",
	HandlerType: (*BeeRemoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _BeeRemote_SubmitJob_Handler,
		},
		{
			MethodName: "UpdateJobs",
			Handler:    _BeeRemote_UpdateJobs_Handler,
		},
		{
			MethodName: "UpdateWork",
			Handler:    _BeeRemote_UpdateWork_Handler,
		},
		{
			MethodName: "GetRSTConfig",
			Handler:    _BeeRemote_GetRSTConfig_Handler,
		},
		{
			MethodName: "GetGlobalFlags",
			Handler:    _BeeRemote_GetGlobalFlags_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdatePaths",
			Handler:       _BeeRemote_UpdatePaths_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetJobs",
			Handler:       _BeeRemote_GetJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "beeremote.proto",
}
